version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: socialtrips_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: socialtrips_root_2025
      MYSQL_DATABASE: socialtrips_db
      MYSQL_USER: socialtrips_user
      MYSQL_PASSWORD: socialtrips_pass_2025
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: