package com.samuel.modelo;
// Generated 15 may 2024 22:01:03 by Hibernate Tools 0.0.1-SNAPSHOT

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;

/**
 * MeGusta generated by hbm2java
 */
@Entity
@Table(name = "me_gusta")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class MeGusta implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	@JsonBackReference
	private Itinerarios itinerarios;
	@JsonBackReference
	private Usuarios usuarios;

	public MeGusta() {
	}

	public MeGusta(Itinerarios itinerarios, Usuarios usuarios) {
		this.itinerarios = itinerarios;
		this.usuarios = usuarios;
	}

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_itinerario", nullable = false)
	public Itinerarios getItinerarios() {
		return this.itinerarios;
	}

	public void setItinerarios(Itinerarios itinerarios) {
		this.itinerarios = itinerarios;
	}

	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_usuario", nullable = false)
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

}
